### ISSUE TITLE
v2alpha/TfModule - list of object implementation

### ISSUE THREAD

**Issue by nicholastcs** [nicholastcs/hclgen#1]
New design for `hclgen.io/generators/v2alpha` for kind `TfModule`

```yaml
# yaml-language-server: $schema=../apis/hclgen.io/generators/v1alpha/TfModule.json
apiVersion: hclgen.io/generators/v2alpha
kind: TfModule
metadata:
  name: test-1
spec:
  module:
    source: app.terraform.io/abc/def1
    version: v12.0-beta22
    variables:
      - name: group
        type: string
        description: The group name of the cluster of services.
        constraint:
          string: 
            minLength: 5
            maxLength: 30
      # unimplemented design below
      - listOf:
          objects: 
            - name: name
              type: string
              description: The name of service.
              constraint:
                string: 
                  minLength: 5
                  maxLength: 30
            - name: cpu
              type: number
              description: The number of vCPU for this service.
              constraint:
                numerical:
                  allowedValues:
                    - 0.5
                    - 1
                    - 2
                    - 4
                    - 8
            - name: memory
              type: number
              description: The memory (MiB) for this service.
              constraint:
                numerical:
                  allowedValues: [256, 512, 1024, 2048]
            - name: is_private
              type: boolean
              description: The VM is private if true.
          constraint:
            list:
              maxCount: 5
              minCount: 1
```

So that the developer can fill in lists of objects and generate its HCL code within the module block.
